import { Inter, Montserrat} from 'next/font/google';
import './globals.css';

// Importamos las fuentes y especificamos los subconjuntos si es necesario
const inter = Inter({ subsets: ['latin'] });
const montserrat = Montserrat({ subsets: ["latin"], weight: "400" });



export const metadata = {
  title: 'My Portfolio AL',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={`${inter.className} ${montserrat.className}`}>{children}</body>
    </html>
  );
}